# Generated by Django 5.0.2 on 2024-02-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('email', models.TextField(max_length=100)),
                ('plano', models.TextField(max_length=100)),
                ('adesao', models.DateField()),
            ],
        ),
    ]
